version: '3'

services:
  rtmp-authenticator:
    image: rtmp-authenticator
  server:
    image: nginx-rtmp
    ports:
      - "1935:1935"
    volumes:
      - ./nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rtmp-authenticator

  video-cutter:
    image: video-cutter 
    command: -i rtmp://server:1935/live/test -vf fps=1/3 -strftime 1 -y "/tmp/photos/%Y-%m-%d_%H-%M-%S.jpg"
    volumes:
      - ./data:/tmp/photos
    depends_on:
      - server
 
  tg-notificator:
    image: tg-notificator
    volumes:
      - ./data:/tmp/photos
    depends_on:
      - video-cutter


