FROM node:10-alpine

RUN mkdir /app

COPY index.js /app
COPY package.json /app 
COPY .env /app
COPY secrets/ app/secrets/

WORKDIR /app

RUN npm install && npm cache clean --force 

CMD ["node", "/app/index.js"]	
